language: generic
sudo: required
services:
  - docker

# build test images
before_install:
  - docker build -t dsknudsen/react-test -f ./client/Dockerfile.dev ./client

# scripts is for testing
scripts:
  - docker run -e CI=true dsknudsen/react-test npm run test

# if tests pass build production images
after_success:
   - docker build -t dsknudsen/complex-client ./client
   - docker build -t dsknudsen/complex-nginx ./nginx
   - docker build -t dsknudsen/complex-server ./server
   - docker build -t dsknudsen/complex-worker ./worker
